name: tests

on:
  push:
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        nim-version: [2.0.0]
        runs-on: [ubuntu-22.04, macos-12, windows-2022]

    name: "nim-${{ matrix.nim-version }}-${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install Nim
        uses: iffy/install-nim@dcaa84c8d3feb17cd7cc10bd124d1658888d9c0e
        with:
          version: "binary:${{ matrix.nim-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: nimble test
